/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl.impl;

import com.pourhashem.xtext.oltl.oltl.Model;
import com.pourhashem.xtext.oltl.oltl.OltlPackage;
import com.pourhashem.xtext.oltl.oltl.SoftFormula;
import com.pourhashem.xtext.oltl.oltl.TempFormula;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.ModelImpl#getBound <em>Bound</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.ModelImpl#getSoftBound <em>Soft Bound</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.ModelImpl#getTempFormula <em>Temp Formula</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.ModelImpl#getSoftFormulae <em>Soft Formulae</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The default value of the '{@link #getBound() <em>Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBound()
   * @generated
   * @ordered
   */
  protected static final int BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getBound() <em>Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBound()
   * @generated
   * @ordered
   */
  protected int bound = BOUND_EDEFAULT;

  /**
   * The default value of the '{@link #getSoftBound() <em>Soft Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSoftBound()
   * @generated
   * @ordered
   */
  protected static final int SOFT_BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSoftBound() <em>Soft Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSoftBound()
   * @generated
   * @ordered
   */
  protected int softBound = SOFT_BOUND_EDEFAULT;

  /**
   * The cached value of the '{@link #getTempFormula() <em>Temp Formula</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTempFormula()
   * @generated
   * @ordered
   */
  protected TempFormula tempFormula;

  /**
   * The cached value of the '{@link #getSoftFormulae() <em>Soft Formulae</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSoftFormulae()
   * @generated
   * @ordered
   */
  protected EList<SoftFormula> softFormulae;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OltlPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getBound()
  {
    return bound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBound(int newBound)
  {
    int oldBound = bound;
    bound = newBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OltlPackage.MODEL__BOUND, oldBound, bound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSoftBound()
  {
    return softBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSoftBound(int newSoftBound)
  {
    int oldSoftBound = softBound;
    softBound = newSoftBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OltlPackage.MODEL__SOFT_BOUND, oldSoftBound, softBound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TempFormula getTempFormula()
  {
    return tempFormula;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTempFormula(TempFormula newTempFormula, NotificationChain msgs)
  {
    TempFormula oldTempFormula = tempFormula;
    tempFormula = newTempFormula;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OltlPackage.MODEL__TEMP_FORMULA, oldTempFormula, newTempFormula);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTempFormula(TempFormula newTempFormula)
  {
    if (newTempFormula != tempFormula)
    {
      NotificationChain msgs = null;
      if (tempFormula != null)
        msgs = ((InternalEObject)tempFormula).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OltlPackage.MODEL__TEMP_FORMULA, null, msgs);
      if (newTempFormula != null)
        msgs = ((InternalEObject)newTempFormula).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OltlPackage.MODEL__TEMP_FORMULA, null, msgs);
      msgs = basicSetTempFormula(newTempFormula, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OltlPackage.MODEL__TEMP_FORMULA, newTempFormula, newTempFormula));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<SoftFormula> getSoftFormulae()
  {
    if (softFormulae == null)
    {
      softFormulae = new EObjectContainmentEList<SoftFormula>(SoftFormula.class, this, OltlPackage.MODEL__SOFT_FORMULAE);
    }
    return softFormulae;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OltlPackage.MODEL__TEMP_FORMULA:
        return basicSetTempFormula(null, msgs);
      case OltlPackage.MODEL__SOFT_FORMULAE:
        return ((InternalEList<?>)getSoftFormulae()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OltlPackage.MODEL__BOUND:
        return getBound();
      case OltlPackage.MODEL__SOFT_BOUND:
        return getSoftBound();
      case OltlPackage.MODEL__TEMP_FORMULA:
        return getTempFormula();
      case OltlPackage.MODEL__SOFT_FORMULAE:
        return getSoftFormulae();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OltlPackage.MODEL__BOUND:
        setBound((Integer)newValue);
        return;
      case OltlPackage.MODEL__SOFT_BOUND:
        setSoftBound((Integer)newValue);
        return;
      case OltlPackage.MODEL__TEMP_FORMULA:
        setTempFormula((TempFormula)newValue);
        return;
      case OltlPackage.MODEL__SOFT_FORMULAE:
        getSoftFormulae().clear();
        getSoftFormulae().addAll((Collection<? extends SoftFormula>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OltlPackage.MODEL__BOUND:
        setBound(BOUND_EDEFAULT);
        return;
      case OltlPackage.MODEL__SOFT_BOUND:
        setSoftBound(SOFT_BOUND_EDEFAULT);
        return;
      case OltlPackage.MODEL__TEMP_FORMULA:
        setTempFormula((TempFormula)null);
        return;
      case OltlPackage.MODEL__SOFT_FORMULAE:
        getSoftFormulae().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OltlPackage.MODEL__BOUND:
        return bound != BOUND_EDEFAULT;
      case OltlPackage.MODEL__SOFT_BOUND:
        return softBound != SOFT_BOUND_EDEFAULT;
      case OltlPackage.MODEL__TEMP_FORMULA:
        return tempFormula != null;
      case OltlPackage.MODEL__SOFT_FORMULAE:
        return softFormulae != null && !softFormulae.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (bound: ");
    result.append(bound);
    result.append(", softBound: ");
    result.append(softBound);
    result.append(')');
    return result.toString();
  }

} //ModelImpl
