/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl.impl;

import com.pourhashem.xtext.oltl.oltl.AP;
import com.pourhashem.xtext.oltl.oltl.OltlPackage;
import com.pourhashem.xtext.oltl.oltl.SoftAllTI;
import com.pourhashem.xtext.oltl.oltl.Weight;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Soft All TI</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.SoftAllTIImpl#getAp <em>Ap</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.SoftAllTIImpl#getId <em>Id</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.SoftAllTIImpl#getWeight <em>Weight</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SoftAllTIImpl extends MinimalEObjectImpl.Container implements SoftAllTI
{
  /**
   * The cached value of the '{@link #getAp() <em>Ap</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAp()
   * @generated
   * @ordered
   */
  protected AP ap;

  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The cached value of the '{@link #getWeight() <em>Weight</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWeight()
   * @generated
   * @ordered
   */
  protected Weight weight;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SoftAllTIImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OltlPackage.Literals.SOFT_ALL_TI;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AP getAp()
  {
    return ap;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAp(AP newAp, NotificationChain msgs)
  {
    AP oldAp = ap;
    ap = newAp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OltlPackage.SOFT_ALL_TI__AP, oldAp, newAp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAp(AP newAp)
  {
    if (newAp != ap)
    {
      NotificationChain msgs = null;
      if (ap != null)
        msgs = ((InternalEObject)ap).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OltlPackage.SOFT_ALL_TI__AP, null, msgs);
      if (newAp != null)
        msgs = ((InternalEObject)newAp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OltlPackage.SOFT_ALL_TI__AP, null, msgs);
      msgs = basicSetAp(newAp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OltlPackage.SOFT_ALL_TI__AP, newAp, newAp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OltlPackage.SOFT_ALL_TI__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Weight getWeight()
  {
    return weight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWeight(Weight newWeight, NotificationChain msgs)
  {
    Weight oldWeight = weight;
    weight = newWeight;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OltlPackage.SOFT_ALL_TI__WEIGHT, oldWeight, newWeight);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWeight(Weight newWeight)
  {
    if (newWeight != weight)
    {
      NotificationChain msgs = null;
      if (weight != null)
        msgs = ((InternalEObject)weight).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OltlPackage.SOFT_ALL_TI__WEIGHT, null, msgs);
      if (newWeight != null)
        msgs = ((InternalEObject)newWeight).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OltlPackage.SOFT_ALL_TI__WEIGHT, null, msgs);
      msgs = basicSetWeight(newWeight, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OltlPackage.SOFT_ALL_TI__WEIGHT, newWeight, newWeight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OltlPackage.SOFT_ALL_TI__AP:
        return basicSetAp(null, msgs);
      case OltlPackage.SOFT_ALL_TI__WEIGHT:
        return basicSetWeight(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OltlPackage.SOFT_ALL_TI__AP:
        return getAp();
      case OltlPackage.SOFT_ALL_TI__ID:
        return getId();
      case OltlPackage.SOFT_ALL_TI__WEIGHT:
        return getWeight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OltlPackage.SOFT_ALL_TI__AP:
        setAp((AP)newValue);
        return;
      case OltlPackage.SOFT_ALL_TI__ID:
        setId((String)newValue);
        return;
      case OltlPackage.SOFT_ALL_TI__WEIGHT:
        setWeight((Weight)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OltlPackage.SOFT_ALL_TI__AP:
        setAp((AP)null);
        return;
      case OltlPackage.SOFT_ALL_TI__ID:
        setId(ID_EDEFAULT);
        return;
      case OltlPackage.SOFT_ALL_TI__WEIGHT:
        setWeight((Weight)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OltlPackage.SOFT_ALL_TI__AP:
        return ap != null;
      case OltlPackage.SOFT_ALL_TI__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case OltlPackage.SOFT_ALL_TI__WEIGHT:
        return weight != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (id: ");
    result.append(id);
    result.append(')');
    return result.toString();
  }

} //SoftAllTIImpl
