/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl.impl;

import com.pourhashem.xtext.oltl.oltl.OltlPackage;
import com.pourhashem.xtext.oltl.oltl.WFloat;
import com.pourhashem.xtext.oltl.oltl.WInt;
import com.pourhashem.xtext.oltl.oltl.Weight;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Weight</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.WeightImpl#getNeg <em>Neg</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.WeightImpl#getWInt <em>WInt</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.impl.WeightImpl#getWFloat <em>WFloat</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WeightImpl extends MinimalEObjectImpl.Container implements Weight
{
  /**
   * The default value of the '{@link #getNeg() <em>Neg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNeg()
   * @generated
   * @ordered
   */
  protected static final String NEG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNeg() <em>Neg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNeg()
   * @generated
   * @ordered
   */
  protected String neg = NEG_EDEFAULT;

  /**
   * The cached value of the '{@link #getWInt() <em>WInt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWInt()
   * @generated
   * @ordered
   */
  protected WInt wInt;

  /**
   * The cached value of the '{@link #getWFloat() <em>WFloat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWFloat()
   * @generated
   * @ordered
   */
  protected WFloat wFloat;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WeightImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OltlPackage.Literals.WEIGHT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNeg()
  {
    return neg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNeg(String newNeg)
  {
    String oldNeg = neg;
    neg = newNeg;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OltlPackage.WEIGHT__NEG, oldNeg, neg));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WInt getWInt()
  {
    return wInt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWInt(WInt newWInt, NotificationChain msgs)
  {
    WInt oldWInt = wInt;
    wInt = newWInt;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OltlPackage.WEIGHT__WINT, oldWInt, newWInt);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWInt(WInt newWInt)
  {
    if (newWInt != wInt)
    {
      NotificationChain msgs = null;
      if (wInt != null)
        msgs = ((InternalEObject)wInt).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OltlPackage.WEIGHT__WINT, null, msgs);
      if (newWInt != null)
        msgs = ((InternalEObject)newWInt).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OltlPackage.WEIGHT__WINT, null, msgs);
      msgs = basicSetWInt(newWInt, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OltlPackage.WEIGHT__WINT, newWInt, newWInt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WFloat getWFloat()
  {
    return wFloat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWFloat(WFloat newWFloat, NotificationChain msgs)
  {
    WFloat oldWFloat = wFloat;
    wFloat = newWFloat;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OltlPackage.WEIGHT__WFLOAT, oldWFloat, newWFloat);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWFloat(WFloat newWFloat)
  {
    if (newWFloat != wFloat)
    {
      NotificationChain msgs = null;
      if (wFloat != null)
        msgs = ((InternalEObject)wFloat).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OltlPackage.WEIGHT__WFLOAT, null, msgs);
      if (newWFloat != null)
        msgs = ((InternalEObject)newWFloat).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OltlPackage.WEIGHT__WFLOAT, null, msgs);
      msgs = basicSetWFloat(newWFloat, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OltlPackage.WEIGHT__WFLOAT, newWFloat, newWFloat));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OltlPackage.WEIGHT__WINT:
        return basicSetWInt(null, msgs);
      case OltlPackage.WEIGHT__WFLOAT:
        return basicSetWFloat(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OltlPackage.WEIGHT__NEG:
        return getNeg();
      case OltlPackage.WEIGHT__WINT:
        return getWInt();
      case OltlPackage.WEIGHT__WFLOAT:
        return getWFloat();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OltlPackage.WEIGHT__NEG:
        setNeg((String)newValue);
        return;
      case OltlPackage.WEIGHT__WINT:
        setWInt((WInt)newValue);
        return;
      case OltlPackage.WEIGHT__WFLOAT:
        setWFloat((WFloat)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OltlPackage.WEIGHT__NEG:
        setNeg(NEG_EDEFAULT);
        return;
      case OltlPackage.WEIGHT__WINT:
        setWInt((WInt)null);
        return;
      case OltlPackage.WEIGHT__WFLOAT:
        setWFloat((WFloat)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OltlPackage.WEIGHT__NEG:
        return NEG_EDEFAULT == null ? neg != null : !NEG_EDEFAULT.equals(neg);
      case OltlPackage.WEIGHT__WINT:
        return wInt != null;
      case OltlPackage.WEIGHT__WFLOAT:
        return wFloat != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (neg: ");
    result.append(neg);
    result.append(')');
    return result.toString();
  }

} //WeightImpl
