/*
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractOltlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.pourhashem.xtext.oltl.oltl.OltlPackage.eINSTANCE);
		return result;
	}
	
}
