/*
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.parser.antlr;

import com.google.inject.Inject;
import com.pourhashem.xtext.oltl.parser.antlr.internal.InternalOltlParser;
import com.pourhashem.xtext.oltl.services.OltlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class OltlParser extends AbstractAntlrParser {

	@Inject
	private OltlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOltlParser createParser(XtextTokenStream stream) {
		return new InternalOltlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public OltlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OltlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
