/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.liTeLLab;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.liTeLLab.AP#getPName <em>PName</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getAP()
 * @model
 * @generated
 */
public interface AP extends EObject
{
  /**
   * Returns the value of the '<em><b>PName</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PName</em>' attribute.
   * @see #setPName(String)
   * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getAP_PName()
   * @model
   * @generated
   */
  String getPName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.liTeLLab.AP#getPName <em>PName</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PName</em>' attribute.
   * @see #getPName()
   * @generated
   */
  void setPName(String value);

} // AP
