/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.liTeLLab;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>VAR</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.liTeLLab.VAR#getVName <em>VName</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getVAR()
 * @model
 * @generated
 */
public interface VAR extends EObject
{
  /**
   * Returns the value of the '<em><b>VName</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>VName</em>' attribute.
   * @see #setVName(String)
   * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getVAR_VName()
   * @model
   * @generated
   */
  String getVName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.liTeLLab.VAR#getVName <em>VName</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>VName</em>' attribute.
   * @see #getVName()
   * @generated
   */
  void setVName(String value);

} // VAR
