/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.liTeLLab;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Weight</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.liTeLLab.Weight#getNeg <em>Neg</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.liTeLLab.Weight#getWInt <em>WInt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.liTeLLab.Weight#getWFloat <em>WFloat</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getWeight()
 * @model
 * @generated
 */
public interface Weight extends EObject
{
  /**
   * Returns the value of the '<em><b>Neg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neg</em>' attribute.
   * @see #setNeg(String)
   * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getWeight_Neg()
   * @model
   * @generated
   */
  String getNeg();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.liTeLLab.Weight#getNeg <em>Neg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neg</em>' attribute.
   * @see #getNeg()
   * @generated
   */
  void setNeg(String value);

  /**
   * Returns the value of the '<em><b>WInt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>WInt</em>' containment reference.
   * @see #setWInt(WInt)
   * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getWeight_WInt()
   * @model containment="true"
   * @generated
   */
  WInt getWInt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.liTeLLab.Weight#getWInt <em>WInt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>WInt</em>' containment reference.
   * @see #getWInt()
   * @generated
   */
  void setWInt(WInt value);

  /**
   * Returns the value of the '<em><b>WFloat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>WFloat</em>' containment reference.
   * @see #setWFloat(WFloat)
   * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getWeight_WFloat()
   * @model containment="true"
   * @generated
   */
  WFloat getWFloat();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.liTeLLab.Weight#getWFloat <em>WFloat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>WFloat</em>' containment reference.
   * @see #getWFloat()
   * @generated
   */
  void setWFloat(WFloat value);

} // Weight
