/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.liTeLLab;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>WInt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.liTeLLab.WInt#getInt <em>Int</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getWInt()
 * @model
 * @generated
 */
public interface WInt extends EObject
{
  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage#getWInt_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.liTeLLab.WInt#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

} // WInt
