/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.LiTeLLab.ui.internal.LiTeLLabActivator;

public class LiTeLLabUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LiTeLLabActivator.getInstance().getInjector("org.xtext.example.mydsl.LiTeLLab");
	}

}
