/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.LiTeLLab.ui.internal.LiTeLLabActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LiTeLLabExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LiTeLLabActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LiTeLLabActivator activator = LiTeLLabActivator.getInstance();
		return activator != null ? activator.getInjector(LiTeLLabActivator.ORG_XTEXT_EXAMPLE_MYDSL_LITELLAB) : null;
	}

}
