/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.ui;

import com.pourhashem.xtext.oltl.ui.AbstractOltlUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OltlUiModule extends AbstractOltlUiModule {
  public OltlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
