/*
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOltlScopeProvider extends DelegatingScopeProvider {
}
