/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.validation;

import com.pourhashem.xtext.oltl.validation.AbstractOltlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class OltlValidator extends AbstractOltlValidator {
}
