/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.AP#getPName <em>PName</em>}</li>
 * </ul>
 *
 * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getAP()
 * @model
 * @generated
 */
public interface AP extends EObject
{
  /**
   * Returns the value of the '<em><b>PName</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>PName</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>PName</em>' attribute.
   * @see #setPName(String)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getAP_PName()
   * @model
   * @generated
   */
  String getPName();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.AP#getPName <em>PName</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PName</em>' attribute.
   * @see #getPName()
   * @generated
   */
  void setPName(String value);

} // AP
