/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.Model#getBound <em>Bound</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.Model#getSoftBound <em>Soft Bound</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.Model#getTempFormula <em>Temp Formula</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.Model#getSoftFormulae <em>Soft Formulae</em>}</li>
 * </ul>
 *
 * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bound</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bound</em>' attribute.
   * @see #setBound(int)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getModel_Bound()
   * @model
   * @generated
   */
  int getBound();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.Model#getBound <em>Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bound</em>' attribute.
   * @see #getBound()
   * @generated
   */
  void setBound(int value);

  /**
   * Returns the value of the '<em><b>Soft Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Soft Bound</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Soft Bound</em>' attribute.
   * @see #setSoftBound(int)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getModel_SoftBound()
   * @model
   * @generated
   */
  int getSoftBound();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.Model#getSoftBound <em>Soft Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Soft Bound</em>' attribute.
   * @see #getSoftBound()
   * @generated
   */
  void setSoftBound(int value);

  /**
   * Returns the value of the '<em><b>Temp Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Temp Formula</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temp Formula</em>' containment reference.
   * @see #setTempFormula(TempFormula)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getModel_TempFormula()
   * @model containment="true"
   * @generated
   */
  TempFormula getTempFormula();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.Model#getTempFormula <em>Temp Formula</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temp Formula</em>' containment reference.
   * @see #getTempFormula()
   * @generated
   */
  void setTempFormula(TempFormula value);

  /**
   * Returns the value of the '<em><b>Soft Formulae</b></em>' containment reference list.
   * The list contents are of type {@link com.pourhashem.xtext.oltl.oltl.SoftFormula}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Soft Formulae</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Soft Formulae</em>' containment reference list.
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getModel_SoftFormulae()
   * @model containment="true"
   * @generated
   */
  EList<SoftFormula> getSoftFormulae();

} // Model
