/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.Model#getTempFormula <em>Temp Formula</em>}</li>
 * </ul>
 *
 * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Temp Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Temp Formula</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temp Formula</em>' containment reference.
   * @see #setTempFormula(TempFormula)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getModel_TempFormula()
   * @model containment="true"
   * @generated
   */
  TempFormula getTempFormula();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.Model#getTempFormula <em>Temp Formula</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temp Formula</em>' containment reference.
   * @see #getTempFormula()
   * @generated
   */
  void setTempFormula(TempFormula value);

} // Model
