/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.pourhashem.xtext.oltl.oltl.OltlFactory
 * @model kind="package"
 * @generated
 */
public interface OltlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "oltl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.pourhashem.com/xtext/oltl/Oltl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "oltl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OltlPackage eINSTANCE = com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl.init();

  /**
   * The meta object id for the '{@link com.pourhashem.xtext.oltl.oltl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.pourhashem.xtext.oltl.oltl.impl.ModelImpl
   * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Temp Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TEMP_FORMULA = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.pourhashem.xtext.oltl.oltl.impl.WeightImpl <em>Weight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.pourhashem.xtext.oltl.oltl.impl.WeightImpl
   * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getWeight()
   * @generated
   */
  int WEIGHT = 1;

  /**
   * The feature id for the '<em><b>Neg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT__NEG = 0;

  /**
   * The feature id for the '<em><b>WInt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT__WINT = 1;

  /**
   * The feature id for the '<em><b>WFloat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT__WFLOAT = 2;

  /**
   * The number of structural features of the '<em>Weight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.pourhashem.xtext.oltl.oltl.impl.WIntImpl <em>WInt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.pourhashem.xtext.oltl.oltl.impl.WIntImpl
   * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getWInt()
   * @generated
   */
  int WINT = 2;

  /**
   * The feature id for the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINT__INT = 0;

  /**
   * The number of structural features of the '<em>WInt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.pourhashem.xtext.oltl.oltl.impl.WFloatImpl <em>WFloat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.pourhashem.xtext.oltl.oltl.impl.WFloatImpl
   * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getWFloat()
   * @generated
   */
  int WFLOAT = 3;

  /**
   * The feature id for the '<em><b>Int1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WFLOAT__INT1 = 0;

  /**
   * The feature id for the '<em><b>Int2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WFLOAT__INT2 = 1;

  /**
   * The number of structural features of the '<em>WFloat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WFLOAT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.pourhashem.xtext.oltl.oltl.impl.TempFormulaImpl <em>Temp Formula</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.pourhashem.xtext.oltl.oltl.impl.TempFormulaImpl
   * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getTempFormula()
   * @generated
   */
  int TEMP_FORMULA = 4;

  /**
   * The feature id for the '<em><b>Ap</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__AP = 0;

  /**
   * The feature id for the '<em><b>Fa</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__FA = 1;

  /**
   * The feature id for the '<em><b>Fo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__FO = 2;

  /**
   * The feature id for the '<em><b>Fnot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__FNOT = 3;

  /**
   * The feature id for the '<em><b>Op2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__OP2 = 4;

  /**
   * The feature id for the '<em><b>F1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__F1 = 5;

  /**
   * The feature id for the '<em><b>F2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__F2 = 6;

  /**
   * The feature id for the '<em><b>Opf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__OPF = 7;

  /**
   * The feature id for the '<em><b>F</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__F = 8;

  /**
   * The feature id for the '<em><b>Weight</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__WEIGHT = 9;

  /**
   * The feature id for the '<em><b>FNext</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__FNEXT = 10;

  /**
   * The feature id for the '<em><b>X1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__X1 = 11;

  /**
   * The feature id for the '<em><b>X2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA__X2 = 12;

  /**
   * The number of structural features of the '<em>Temp Formula</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMP_FORMULA_FEATURE_COUNT = 13;

  /**
   * The meta object id for the '{@link com.pourhashem.xtext.oltl.oltl.impl.APImpl <em>AP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.pourhashem.xtext.oltl.oltl.impl.APImpl
   * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getAP()
   * @generated
   */
  int AP = 5;

  /**
   * The feature id for the '<em><b>PName</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AP__PNAME = 0;

  /**
   * The number of structural features of the '<em>AP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AP_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link com.pourhashem.xtext.oltl.oltl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.Model#getTempFormula <em>Temp Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Temp Formula</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.Model#getTempFormula()
   * @see #getModel()
   * @generated
   */
  EReference getModel_TempFormula();

  /**
   * Returns the meta object for class '{@link com.pourhashem.xtext.oltl.oltl.Weight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Weight</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.Weight
   * @generated
   */
  EClass getWeight();

  /**
   * Returns the meta object for the attribute '{@link com.pourhashem.xtext.oltl.oltl.Weight#getNeg <em>Neg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Neg</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.Weight#getNeg()
   * @see #getWeight()
   * @generated
   */
  EAttribute getWeight_Neg();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.Weight#getWInt <em>WInt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>WInt</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.Weight#getWInt()
   * @see #getWeight()
   * @generated
   */
  EReference getWeight_WInt();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.Weight#getWFloat <em>WFloat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>WFloat</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.Weight#getWFloat()
   * @see #getWeight()
   * @generated
   */
  EReference getWeight_WFloat();

  /**
   * Returns the meta object for class '{@link com.pourhashem.xtext.oltl.oltl.WInt <em>WInt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>WInt</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.WInt
   * @generated
   */
  EClass getWInt();

  /**
   * Returns the meta object for the attribute '{@link com.pourhashem.xtext.oltl.oltl.WInt#getInt <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.WInt#getInt()
   * @see #getWInt()
   * @generated
   */
  EAttribute getWInt_Int();

  /**
   * Returns the meta object for class '{@link com.pourhashem.xtext.oltl.oltl.WFloat <em>WFloat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>WFloat</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.WFloat
   * @generated
   */
  EClass getWFloat();

  /**
   * Returns the meta object for the attribute '{@link com.pourhashem.xtext.oltl.oltl.WFloat#getInt1 <em>Int1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int1</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.WFloat#getInt1()
   * @see #getWFloat()
   * @generated
   */
  EAttribute getWFloat_Int1();

  /**
   * Returns the meta object for the attribute '{@link com.pourhashem.xtext.oltl.oltl.WFloat#getInt2 <em>Int2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int2</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.WFloat#getInt2()
   * @see #getWFloat()
   * @generated
   */
  EAttribute getWFloat_Int2();

  /**
   * Returns the meta object for class '{@link com.pourhashem.xtext.oltl.oltl.TempFormula <em>Temp Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Temp Formula</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula
   * @generated
   */
  EClass getTempFormula();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getAp <em>Ap</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ap</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getAp()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_Ap();

  /**
   * Returns the meta object for the containment reference list '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFa <em>Fa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fa</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getFa()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_Fa();

  /**
   * Returns the meta object for the containment reference list '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFo <em>Fo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fo</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getFo()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_Fo();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFnot <em>Fnot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fnot</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getFnot()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_Fnot();

  /**
   * Returns the meta object for the attribute '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getOp2 <em>Op2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op2</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getOp2()
   * @see #getTempFormula()
   * @generated
   */
  EAttribute getTempFormula_Op2();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getF1 <em>F1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>F1</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getF1()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_F1();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getF2 <em>F2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>F2</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getF2()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_F2();

  /**
   * Returns the meta object for the attribute '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getOpf <em>Opf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Opf</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getOpf()
   * @see #getTempFormula()
   * @generated
   */
  EAttribute getTempFormula_Opf();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getF <em>F</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>F</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getF()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_F();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Weight</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getWeight()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_Weight();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFNext <em>FNext</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>FNext</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getFNext()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_FNext();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getX1 <em>X1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>X1</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getX1()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_X1();

  /**
   * Returns the meta object for the containment reference '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getX2 <em>X2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>X2</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.TempFormula#getX2()
   * @see #getTempFormula()
   * @generated
   */
  EReference getTempFormula_X2();

  /**
   * Returns the meta object for class '{@link com.pourhashem.xtext.oltl.oltl.AP <em>AP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AP</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.AP
   * @generated
   */
  EClass getAP();

  /**
   * Returns the meta object for the attribute '{@link com.pourhashem.xtext.oltl.oltl.AP#getPName <em>PName</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>PName</em>'.
   * @see com.pourhashem.xtext.oltl.oltl.AP#getPName()
   * @see #getAP()
   * @generated
   */
  EAttribute getAP_PName();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  OltlFactory getOltlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.pourhashem.xtext.oltl.oltl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.pourhashem.xtext.oltl.oltl.impl.ModelImpl
     * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Temp Formula</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TEMP_FORMULA = eINSTANCE.getModel_TempFormula();

    /**
     * The meta object literal for the '{@link com.pourhashem.xtext.oltl.oltl.impl.WeightImpl <em>Weight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.pourhashem.xtext.oltl.oltl.impl.WeightImpl
     * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getWeight()
     * @generated
     */
    EClass WEIGHT = eINSTANCE.getWeight();

    /**
     * The meta object literal for the '<em><b>Neg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WEIGHT__NEG = eINSTANCE.getWeight_Neg();

    /**
     * The meta object literal for the '<em><b>WInt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WEIGHT__WINT = eINSTANCE.getWeight_WInt();

    /**
     * The meta object literal for the '<em><b>WFloat</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WEIGHT__WFLOAT = eINSTANCE.getWeight_WFloat();

    /**
     * The meta object literal for the '{@link com.pourhashem.xtext.oltl.oltl.impl.WIntImpl <em>WInt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.pourhashem.xtext.oltl.oltl.impl.WIntImpl
     * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getWInt()
     * @generated
     */
    EClass WINT = eINSTANCE.getWInt();

    /**
     * The meta object literal for the '<em><b>Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WINT__INT = eINSTANCE.getWInt_Int();

    /**
     * The meta object literal for the '{@link com.pourhashem.xtext.oltl.oltl.impl.WFloatImpl <em>WFloat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.pourhashem.xtext.oltl.oltl.impl.WFloatImpl
     * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getWFloat()
     * @generated
     */
    EClass WFLOAT = eINSTANCE.getWFloat();

    /**
     * The meta object literal for the '<em><b>Int1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WFLOAT__INT1 = eINSTANCE.getWFloat_Int1();

    /**
     * The meta object literal for the '<em><b>Int2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WFLOAT__INT2 = eINSTANCE.getWFloat_Int2();

    /**
     * The meta object literal for the '{@link com.pourhashem.xtext.oltl.oltl.impl.TempFormulaImpl <em>Temp Formula</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.pourhashem.xtext.oltl.oltl.impl.TempFormulaImpl
     * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getTempFormula()
     * @generated
     */
    EClass TEMP_FORMULA = eINSTANCE.getTempFormula();

    /**
     * The meta object literal for the '<em><b>Ap</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__AP = eINSTANCE.getTempFormula_Ap();

    /**
     * The meta object literal for the '<em><b>Fa</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__FA = eINSTANCE.getTempFormula_Fa();

    /**
     * The meta object literal for the '<em><b>Fo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__FO = eINSTANCE.getTempFormula_Fo();

    /**
     * The meta object literal for the '<em><b>Fnot</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__FNOT = eINSTANCE.getTempFormula_Fnot();

    /**
     * The meta object literal for the '<em><b>Op2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEMP_FORMULA__OP2 = eINSTANCE.getTempFormula_Op2();

    /**
     * The meta object literal for the '<em><b>F1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__F1 = eINSTANCE.getTempFormula_F1();

    /**
     * The meta object literal for the '<em><b>F2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__F2 = eINSTANCE.getTempFormula_F2();

    /**
     * The meta object literal for the '<em><b>Opf</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEMP_FORMULA__OPF = eINSTANCE.getTempFormula_Opf();

    /**
     * The meta object literal for the '<em><b>F</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__F = eINSTANCE.getTempFormula_F();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__WEIGHT = eINSTANCE.getTempFormula_Weight();

    /**
     * The meta object literal for the '<em><b>FNext</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__FNEXT = eINSTANCE.getTempFormula_FNext();

    /**
     * The meta object literal for the '<em><b>X1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__X1 = eINSTANCE.getTempFormula_X1();

    /**
     * The meta object literal for the '<em><b>X2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEMP_FORMULA__X2 = eINSTANCE.getTempFormula_X2();

    /**
     * The meta object literal for the '{@link com.pourhashem.xtext.oltl.oltl.impl.APImpl <em>AP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.pourhashem.xtext.oltl.oltl.impl.APImpl
     * @see com.pourhashem.xtext.oltl.oltl.impl.OltlPackageImpl#getAP()
     * @generated
     */
    EClass AP = eINSTANCE.getAP();

    /**
     * The meta object literal for the '<em><b>PName</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AP__PNAME = eINSTANCE.getAP_PName();

  }

} //OltlPackage
