/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Soft TI</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.SoftTI#getAp <em>Ap</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.SoftTI#getTi <em>Ti</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.SoftTI#getId <em>Id</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.SoftTI#getWeight <em>Weight</em>}</li>
 * </ul>
 *
 * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getSoftTI()
 * @model
 * @generated
 */
public interface SoftTI extends EObject
{
  /**
   * Returns the value of the '<em><b>Ap</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ap</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ap</em>' containment reference.
   * @see #setAp(AP)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getSoftTI_Ap()
   * @model containment="true"
   * @generated
   */
  AP getAp();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.SoftTI#getAp <em>Ap</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ap</em>' containment reference.
   * @see #getAp()
   * @generated
   */
  void setAp(AP value);

  /**
   * Returns the value of the '<em><b>Ti</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ti</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ti</em>' attribute.
   * @see #setTi(int)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getSoftTI_Ti()
   * @model
   * @generated
   */
  int getTi();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.SoftTI#getTi <em>Ti</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ti</em>' attribute.
   * @see #getTi()
   * @generated
   */
  void setTi(int value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getSoftTI_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.SoftTI#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Weight</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Weight</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight</em>' containment reference.
   * @see #setWeight(Weight)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getSoftTI_Weight()
   * @model containment="true"
   * @generated
   */
  Weight getWeight();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.SoftTI#getWeight <em>Weight</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight</em>' containment reference.
   * @see #getWeight()
   * @generated
   */
  void setWeight(Weight value);

} // SoftTI
