/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Soft Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.SoftFormula#getSoftAll <em>Soft All</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.SoftFormula#getSoftAt <em>Soft At</em>}</li>
 * </ul>
 *
 * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getSoftFormula()
 * @model
 * @generated
 */
public interface SoftFormula extends EObject
{
  /**
   * Returns the value of the '<em><b>Soft All</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Soft All</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Soft All</em>' containment reference.
   * @see #setSoftAll(SoftAllTI)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getSoftFormula_SoftAll()
   * @model containment="true"
   * @generated
   */
  SoftAllTI getSoftAll();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.SoftFormula#getSoftAll <em>Soft All</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Soft All</em>' containment reference.
   * @see #getSoftAll()
   * @generated
   */
  void setSoftAll(SoftAllTI value);

  /**
   * Returns the value of the '<em><b>Soft At</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Soft At</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Soft At</em>' containment reference.
   * @see #setSoftAt(SoftTI)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getSoftFormula_SoftAt()
   * @model containment="true"
   * @generated
   */
  SoftTI getSoftAt();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.SoftFormula#getSoftAt <em>Soft At</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Soft At</em>' containment reference.
   * @see #getSoftAt()
   * @generated
   */
  void setSoftAt(SoftTI value);

} // SoftFormula
