/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Temp Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getAp <em>Ap</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFa <em>Fa</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFo <em>Fo</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFnot <em>Fnot</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getOp2 <em>Op2</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getF1 <em>F1</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getF2 <em>F2</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getOpf <em>Opf</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getF <em>F</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getWeight <em>Weight</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFNext <em>FNext</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getX1 <em>X1</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getX2 <em>X2</em>}</li>
 * </ul>
 *
 * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula()
 * @model
 * @generated
 */
public interface TempFormula extends EObject
{
  /**
   * Returns the value of the '<em><b>Ap</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ap</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ap</em>' containment reference.
   * @see #setAp(AP)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_Ap()
   * @model containment="true"
   * @generated
   */
  AP getAp();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getAp <em>Ap</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ap</em>' containment reference.
   * @see #getAp()
   * @generated
   */
  void setAp(AP value);

  /**
   * Returns the value of the '<em><b>Fa</b></em>' containment reference list.
   * The list contents are of type {@link com.pourhashem.xtext.oltl.oltl.TempFormula}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fa</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fa</em>' containment reference list.
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_Fa()
   * @model containment="true"
   * @generated
   */
  EList<TempFormula> getFa();

  /**
   * Returns the value of the '<em><b>Fo</b></em>' containment reference list.
   * The list contents are of type {@link com.pourhashem.xtext.oltl.oltl.TempFormula}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fo</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fo</em>' containment reference list.
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_Fo()
   * @model containment="true"
   * @generated
   */
  EList<TempFormula> getFo();

  /**
   * Returns the value of the '<em><b>Fnot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fnot</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fnot</em>' containment reference.
   * @see #setFnot(TempFormula)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_Fnot()
   * @model containment="true"
   * @generated
   */
  TempFormula getFnot();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFnot <em>Fnot</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fnot</em>' containment reference.
   * @see #getFnot()
   * @generated
   */
  void setFnot(TempFormula value);

  /**
   * Returns the value of the '<em><b>Op2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op2</em>' attribute.
   * @see #setOp2(String)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_Op2()
   * @model
   * @generated
   */
  String getOp2();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getOp2 <em>Op2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op2</em>' attribute.
   * @see #getOp2()
   * @generated
   */
  void setOp2(String value);

  /**
   * Returns the value of the '<em><b>F1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F1</em>' containment reference.
   * @see #setF1(TempFormula)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_F1()
   * @model containment="true"
   * @generated
   */
  TempFormula getF1();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getF1 <em>F1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F1</em>' containment reference.
   * @see #getF1()
   * @generated
   */
  void setF1(TempFormula value);

  /**
   * Returns the value of the '<em><b>F2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F2</em>' containment reference.
   * @see #setF2(TempFormula)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_F2()
   * @model containment="true"
   * @generated
   */
  TempFormula getF2();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getF2 <em>F2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F2</em>' containment reference.
   * @see #getF2()
   * @generated
   */
  void setF2(TempFormula value);

  /**
   * Returns the value of the '<em><b>Opf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Opf</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opf</em>' attribute.
   * @see #setOpf(String)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_Opf()
   * @model
   * @generated
   */
  String getOpf();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getOpf <em>Opf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opf</em>' attribute.
   * @see #getOpf()
   * @generated
   */
  void setOpf(String value);

  /**
   * Returns the value of the '<em><b>F</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' containment reference.
   * @see #setF(TempFormula)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_F()
   * @model containment="true"
   * @generated
   */
  TempFormula getF();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getF <em>F</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F</em>' containment reference.
   * @see #getF()
   * @generated
   */
  void setF(TempFormula value);

  /**
   * Returns the value of the '<em><b>Weight</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Weight</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight</em>' containment reference.
   * @see #setWeight(Weight)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_Weight()
   * @model containment="true"
   * @generated
   */
  Weight getWeight();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getWeight <em>Weight</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight</em>' containment reference.
   * @see #getWeight()
   * @generated
   */
  void setWeight(Weight value);

  /**
   * Returns the value of the '<em><b>FNext</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>FNext</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>FNext</em>' containment reference.
   * @see #setFNext(TempFormula)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_FNext()
   * @model containment="true"
   * @generated
   */
  TempFormula getFNext();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getFNext <em>FNext</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>FNext</em>' containment reference.
   * @see #getFNext()
   * @generated
   */
  void setFNext(TempFormula value);

  /**
   * Returns the value of the '<em><b>X1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X1</em>' containment reference.
   * @see #setX1(WInt)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_X1()
   * @model containment="true"
   * @generated
   */
  WInt getX1();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getX1 <em>X1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X1</em>' containment reference.
   * @see #getX1()
   * @generated
   */
  void setX1(WInt value);

  /**
   * Returns the value of the '<em><b>X2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X2</em>' containment reference.
   * @see #setX2(WInt)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getTempFormula_X2()
   * @model containment="true"
   * @generated
   */
  WInt getX2();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.TempFormula#getX2 <em>X2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X2</em>' containment reference.
   * @see #getX2()
   * @generated
   */
  void setX2(WInt value);

} // TempFormula
