/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Weight</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.Weight#getNeg <em>Neg</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.Weight#getWInt <em>WInt</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.Weight#getWFloat <em>WFloat</em>}</li>
 * </ul>
 *
 * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getWeight()
 * @model
 * @generated
 */
public interface Weight extends EObject
{
  /**
   * Returns the value of the '<em><b>Neg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Neg</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neg</em>' attribute.
   * @see #setNeg(String)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getWeight_Neg()
   * @model
   * @generated
   */
  String getNeg();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.Weight#getNeg <em>Neg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neg</em>' attribute.
   * @see #getNeg()
   * @generated
   */
  void setNeg(String value);

  /**
   * Returns the value of the '<em><b>WInt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>WInt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>WInt</em>' containment reference.
   * @see #setWInt(WInt)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getWeight_WInt()
   * @model containment="true"
   * @generated
   */
  WInt getWInt();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.Weight#getWInt <em>WInt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>WInt</em>' containment reference.
   * @see #getWInt()
   * @generated
   */
  void setWInt(WInt value);

  /**
   * Returns the value of the '<em><b>WFloat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>WFloat</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>WFloat</em>' containment reference.
   * @see #setWFloat(WFloat)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getWeight_WFloat()
   * @model containment="true"
   * @generated
   */
  WFloat getWFloat();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.Weight#getWFloat <em>WFloat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>WFloat</em>' containment reference.
   * @see #getWFloat()
   * @generated
   */
  void setWFloat(WFloat value);

} // Weight
