/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.oltl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>WFloat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.WFloat#getInt1 <em>Int1</em>}</li>
 *   <li>{@link com.pourhashem.xtext.oltl.oltl.WFloat#getInt2 <em>Int2</em>}</li>
 * </ul>
 *
 * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getWFloat()
 * @model
 * @generated
 */
public interface WFloat extends EObject
{
  /**
   * Returns the value of the '<em><b>Int1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int1</em>' attribute.
   * @see #setInt1(int)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getWFloat_Int1()
   * @model
   * @generated
   */
  int getInt1();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.WFloat#getInt1 <em>Int1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int1</em>' attribute.
   * @see #getInt1()
   * @generated
   */
  void setInt1(int value);

  /**
   * Returns the value of the '<em><b>Int2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int2</em>' attribute.
   * @see #setInt2(int)
   * @see com.pourhashem.xtext.oltl.oltl.OltlPackage#getWFloat_Int2()
   * @model
   * @generated
   */
  int getInt2();

  /**
   * Sets the value of the '{@link com.pourhashem.xtext.oltl.oltl.WFloat#getInt2 <em>Int2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int2</em>' attribute.
   * @see #getInt2()
   * @generated
   */
  void setInt2(int value);

} // WFloat
