/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LiTeLLabUiModule extends AbstractLiTeLLabUiModule {

	public LiTeLLabUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
