/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.liTeLLab.AP;
import org.xtext.example.mydsl.liTeLLab.LiTeLLabPackage;
import org.xtext.example.mydsl.liTeLLab.Model;
import org.xtext.example.mydsl.liTeLLab.TempFormula;
import org.xtext.example.mydsl.liTeLLab.TempTerm;
import org.xtext.example.mydsl.liTeLLab.VAR;
import org.xtext.example.mydsl.liTeLLab.WFloat;
import org.xtext.example.mydsl.liTeLLab.WInt;
import org.xtext.example.mydsl.liTeLLab.Weight;
import org.xtext.example.mydsl.liTeLLab.oldVAR;
import org.xtext.example.mydsl.services.LiTeLLabGrammarAccess;

@SuppressWarnings("all")
public class LiTeLLabSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private LiTeLLabGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == LiTeLLabPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case LiTeLLabPackage.AP:
				sequence_AP(context, (AP) semanticObject); 
				return; 
			case LiTeLLabPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case LiTeLLabPackage.TEMP_FORMULA:
				sequence_TempFormula(context, (TempFormula) semanticObject); 
				return; 
			case LiTeLLabPackage.TEMP_TERM:
				sequence_TempTerm(context, (TempTerm) semanticObject); 
				return; 
			case LiTeLLabPackage.VAR:
				sequence_VAR(context, (VAR) semanticObject); 
				return; 
			case LiTeLLabPackage.WFLOAT:
				sequence_WFloat(context, (WFloat) semanticObject); 
				return; 
			case LiTeLLabPackage.WINT:
				sequence_WInt(context, (WInt) semanticObject); 
				return; 
			case LiTeLLabPackage.WEIGHT:
				sequence_Weight(context, (Weight) semanticObject); 
				return; 
			case LiTeLLabPackage.OLD_VAR:
				sequence_oldVAR(context, (oldVAR) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     AP returns AP
	 *
	 * Constraint:
	 *     pName=ID
	 * </pre>
	 */
	protected void sequence_AP(ISerializationContext context, AP semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LiTeLLabPackage.Literals.AP__PNAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LiTeLLabPackage.Literals.AP__PNAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAPAccess().getPNameIDTerminalRuleCall_4_0(), semanticObject.getPName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     tempFormula=TempFormula
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LiTeLLabPackage.Literals.MODEL__TEMP_FORMULA) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LiTeLLabPackage.Literals.MODEL__TEMP_FORMULA));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getModelAccess().getTempFormulaTempFormulaParserRuleCall_0(), semanticObject.getTempFormula());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TempFormula returns TempFormula
	 *
	 * Constraint:
	 *     (
	 *         ap=AP | 
	 *         fa+=TempFormula+ | 
	 *         fo+=TempFormula+ | 
	 *         fnot=TempFormula | 
	 *         (op2=OP2 f1=TempFormula f2=TempFormula) | 
	 *         (opf=OPF f=TempFormula) | 
	 *         (ap=AP weight=Weight) | 
	 *         (iap=AP weight=Weight) | 
	 *         (fNext=TempFormula x1=WInt x2=WInt?) | 
	 *         (comp=COMP tt1=TempTerm tt2=TempTerm)
	 *     )
	 * </pre>
	 */
	protected void sequence_TempFormula(ISerializationContext context, TempFormula semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TempTerm returns TempTerm
	 *
	 * Constraint:
	 *     (int1=INT | var=VAR | oldVar=oldVAR)
	 * </pre>
	 */
	protected void sequence_TempTerm(ISerializationContext context, TempTerm semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     VAR returns VAR
	 *
	 * Constraint:
	 *     vName=ID
	 * </pre>
	 */
	protected void sequence_VAR(ISerializationContext context, VAR semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LiTeLLabPackage.Literals.VAR__VNAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LiTeLLabPackage.Literals.VAR__VNAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVARAccess().getVNameIDTerminalRuleCall_4_0(), semanticObject.getVName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     WFloat returns WFloat
	 *
	 * Constraint:
	 *     (int1=INT int2=INT)
	 * </pre>
	 */
	protected void sequence_WFloat(ISerializationContext context, WFloat semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LiTeLLabPackage.Literals.WFLOAT__INT1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LiTeLLabPackage.Literals.WFLOAT__INT1));
			if (transientValues.isValueTransient(semanticObject, LiTeLLabPackage.Literals.WFLOAT__INT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LiTeLLabPackage.Literals.WFLOAT__INT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWFloatAccess().getInt1INTTerminalRuleCall_0_0(), semanticObject.getInt1());
		feeder.accept(grammarAccess.getWFloatAccess().getInt2INTTerminalRuleCall_2_0(), semanticObject.getInt2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     WInt returns WInt
	 *
	 * Constraint:
	 *     int=INT
	 * </pre>
	 */
	protected void sequence_WInt(ISerializationContext context, WInt semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LiTeLLabPackage.Literals.WINT__INT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LiTeLLabPackage.Literals.WINT__INT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWIntAccess().getIntINTTerminalRuleCall_0(), semanticObject.getInt());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Weight returns Weight
	 *
	 * Constraint:
	 *     (neg='-'? (wInt=WInt | wFloat=WFloat))
	 * </pre>
	 */
	protected void sequence_Weight(ISerializationContext context, Weight semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     oldVAR returns oldVAR
	 *
	 * Constraint:
	 *     var=VAR
	 * </pre>
	 */
	protected void sequence_oldVAR(ISerializationContext context, oldVAR semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LiTeLLabPackage.Literals.OLD_VAR__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LiTeLLabPackage.Literals.OLD_VAR__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOldVARAccess().getVarVARParserRuleCall_2_0(), semanticObject.getVar());
		feeder.finish();
	}
	
	
}
