/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.LiTeLLabGrammarAccess;

@SuppressWarnings("all")
public class LiTeLLabSyntacticSequencer extends AbstractSyntacticSequencer {

	protected LiTeLLabGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AP_PKeyword_2_0_or_PKeyword_2_1;
	protected AbstractElementAlias match_VAR_VKeyword_2_0_or_VKeyword_2_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (LiTeLLabGrammarAccess) access;
		match_AP_PKeyword_2_0_or_PKeyword_2_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getAPAccess().getPKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getAPAccess().getPKeyword_2_1()));
		match_VAR_VKeyword_2_0_or_VKeyword_2_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getVARAccess().getVKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVARAccess().getVKeyword_2_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_AP_PKeyword_2_0_or_PKeyword_2_1.equals(syntax))
				emit_AP_PKeyword_2_0_or_PKeyword_2_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VAR_VKeyword_2_0_or_VKeyword_2_1.equals(syntax))
				emit_VAR_VKeyword_2_0_or_VKeyword_2_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'P' | 'p'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '(' '-' (ambiguity) '-' pName=ID
	 
	 * </pre>
	 */
	protected void emit_AP_PKeyword_2_0_or_PKeyword_2_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'V' | 'v'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '(' '-' (ambiguity) '-' vName=ID
	 
	 * </pre>
	 */
	protected void emit_VAR_VKeyword_2_0_or_VKeyword_2_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
