/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl;

import com.pourhashem.xtext.oltl.OltlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OltlStandaloneSetup extends OltlStandaloneSetupGenerated {
  public static void doSetup() {
    OltlStandaloneSetup _oltlStandaloneSetup = new OltlStandaloneSetup();
    _oltlStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
