/**
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl;

import com.pourhashem.xtext.oltl.AbstractOltlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OltlRuntimeModule extends AbstractOltlRuntimeModule {
}
