/*
 * generated by Xtext 2.10.0
 */
package com.pourhashem.xtext.oltl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class OltlGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBoundKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cBoundAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cBoundINTTerminalRuleCall_1_0 = (RuleCall)cBoundAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cSoftBoundKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSoftBoundAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSoftBoundINTTerminalRuleCall_2_1_0 = (RuleCall)cSoftBoundAssignment_2_1.eContents().get(0);
		private final Keyword cFormulaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTempFormulaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTempFormulaTempFormulaParserRuleCall_4_0 = (RuleCall)cTempFormulaAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSoftFormulaeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSoftFormulaeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cSoftFormulaeSoftFormulaParserRuleCall_5_1_0 = (RuleCall)cSoftFormulaeAssignment_5_1.eContents().get(0);
		
		//Model:
		//	'Bound:' bound=INT ('SoftBound:' softBound=INT)?
		//	'Formula:' tempFormula=TempFormula ('SoftFormulae:' softFormulae+=SoftFormula*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Bound:' bound=INT ('SoftBound:' softBound=INT)? 'Formula:' tempFormula=TempFormula ('SoftFormulae:'
		//softFormulae+=SoftFormula*)?
		public Group getGroup() { return cGroup; }
		
		//'Bound:'
		public Keyword getBoundKeyword_0() { return cBoundKeyword_0; }
		
		//bound=INT
		public Assignment getBoundAssignment_1() { return cBoundAssignment_1; }
		
		//INT
		public RuleCall getBoundINTTerminalRuleCall_1_0() { return cBoundINTTerminalRuleCall_1_0; }
		
		//('SoftBound:' softBound=INT)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'SoftBound:'
		public Keyword getSoftBoundKeyword_2_0() { return cSoftBoundKeyword_2_0; }
		
		//softBound=INT
		public Assignment getSoftBoundAssignment_2_1() { return cSoftBoundAssignment_2_1; }
		
		//INT
		public RuleCall getSoftBoundINTTerminalRuleCall_2_1_0() { return cSoftBoundINTTerminalRuleCall_2_1_0; }
		
		//'Formula:'
		public Keyword getFormulaKeyword_3() { return cFormulaKeyword_3; }
		
		//tempFormula=TempFormula
		public Assignment getTempFormulaAssignment_4() { return cTempFormulaAssignment_4; }
		
		//TempFormula
		public RuleCall getTempFormulaTempFormulaParserRuleCall_4_0() { return cTempFormulaTempFormulaParserRuleCall_4_0; }
		
		//('SoftFormulae:' softFormulae+=SoftFormula*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'SoftFormulae:'
		public Keyword getSoftFormulaeKeyword_5_0() { return cSoftFormulaeKeyword_5_0; }
		
		//softFormulae+=SoftFormula*
		public Assignment getSoftFormulaeAssignment_5_1() { return cSoftFormulaeAssignment_5_1; }
		
		//SoftFormula
		public RuleCall getSoftFormulaeSoftFormulaParserRuleCall_5_1_0() { return cSoftFormulaeSoftFormulaParserRuleCall_5_1_0; }
	}
	public class SoftFormulaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.SoftFormula");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cSoftAllAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cSoftAllSoftAllTIParserRuleCall_0_0 = (RuleCall)cSoftAllAssignment_0.eContents().get(0);
		private final Assignment cSoftAtAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cSoftAtSoftTIParserRuleCall_1_0 = (RuleCall)cSoftAtAssignment_1.eContents().get(0);
		
		//SoftFormula:
		//	softAll=SoftAllTI | softAt=SoftTI;
		@Override public ParserRule getRule() { return rule; }
		
		//softAll=SoftAllTI | softAt=SoftTI
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//softAll=SoftAllTI
		public Assignment getSoftAllAssignment_0() { return cSoftAllAssignment_0; }
		
		//SoftAllTI
		public RuleCall getSoftAllSoftAllTIParserRuleCall_0_0() { return cSoftAllSoftAllTIParserRuleCall_0_0; }
		
		//softAt=SoftTI
		public Assignment getSoftAtAssignment_1() { return cSoftAtAssignment_1; }
		
		//SoftTI
		public RuleCall getSoftAtSoftTIParserRuleCall_1_0() { return cSoftAtSoftTIParserRuleCall_1_0; }
	}
	public class SoftAllTIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.SoftAllTI");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cSoftKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cApAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cApAPParserRuleCall_2_0 = (RuleCall)cApAssignment_2.eContents().get(0);
		private final Assignment cIdAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIdIDTerminalRuleCall_3_0 = (RuleCall)cIdAssignment_3.eContents().get(0);
		private final Assignment cWeightAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cWeightWeightParserRuleCall_4_0 = (RuleCall)cWeightAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SoftAllTI:
		//	'(' 'soft' ap=AP id=ID? weight=Weight ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' 'soft' ap=AP id=ID? weight=Weight ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//'soft'
		public Keyword getSoftKeyword_1() { return cSoftKeyword_1; }
		
		//ap=AP
		public Assignment getApAssignment_2() { return cApAssignment_2; }
		
		//AP
		public RuleCall getApAPParserRuleCall_2_0() { return cApAPParserRuleCall_2_0; }
		
		//id=ID?
		public Assignment getIdAssignment_3() { return cIdAssignment_3; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_3_0() { return cIdIDTerminalRuleCall_3_0; }
		
		//weight=Weight
		public Assignment getWeightAssignment_4() { return cWeightAssignment_4; }
		
		//Weight
		public RuleCall getWeightWeightParserRuleCall_4_0() { return cWeightWeightParserRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class SoftTIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.SoftTI");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cSoftKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCommercialAtKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cApAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cApAPParserRuleCall_4_0 = (RuleCall)cApAssignment_4.eContents().get(0);
		private final Assignment cTiAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTiINTTerminalRuleCall_5_0 = (RuleCall)cTiAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cIdAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cIdIDTerminalRuleCall_7_0 = (RuleCall)cIdAssignment_7.eContents().get(0);
		private final Assignment cWeightAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cWeightWeightParserRuleCall_8_0 = (RuleCall)cWeightAssignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//SoftTI:
		//	'(' 'soft' '(' '@' ap=AP ti=INT ')' id=ID? weight=Weight ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' 'soft' '(' '@' ap=AP ti=INT ')' id=ID? weight=Weight ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//'soft'
		public Keyword getSoftKeyword_1() { return cSoftKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//'@'
		public Keyword getCommercialAtKeyword_3() { return cCommercialAtKeyword_3; }
		
		//ap=AP
		public Assignment getApAssignment_4() { return cApAssignment_4; }
		
		//AP
		public RuleCall getApAPParserRuleCall_4_0() { return cApAPParserRuleCall_4_0; }
		
		//ti=INT
		public Assignment getTiAssignment_5() { return cTiAssignment_5; }
		
		//INT
		public RuleCall getTiINTTerminalRuleCall_5_0() { return cTiINTTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//id=ID?
		public Assignment getIdAssignment_7() { return cIdAssignment_7; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_7_0() { return cIdIDTerminalRuleCall_7_0; }
		
		//weight=Weight
		public Assignment getWeightAssignment_8() { return cWeightAssignment_8; }
		
		//Weight
		public RuleCall getWeightWeightParserRuleCall_8_0() { return cWeightWeightParserRuleCall_8_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
	}
	public class WeightElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.Weight");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cWIntAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cWIntWIntParserRuleCall_0_0 = (RuleCall)cWIntAssignment_0.eContents().get(0);
		private final Assignment cWFloatAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cWFloatWFloatParserRuleCall_1_0 = (RuleCall)cWFloatAssignment_1.eContents().get(0);
		
		//Weight:
		//	wInt=WInt | wFloat=WFloat;
		@Override public ParserRule getRule() { return rule; }
		
		//wInt=WInt | wFloat=WFloat
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//wInt=WInt
		public Assignment getWIntAssignment_0() { return cWIntAssignment_0; }
		
		//WInt
		public RuleCall getWIntWIntParserRuleCall_0_0() { return cWIntWIntParserRuleCall_0_0; }
		
		//wFloat=WFloat
		public Assignment getWFloatAssignment_1() { return cWFloatAssignment_1; }
		
		//WFloat
		public RuleCall getWFloatWFloatParserRuleCall_1_0() { return cWFloatWFloatParserRuleCall_1_0; }
	}
	public class WIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.WInt");
		private final Assignment cIntAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIntINTTerminalRuleCall_0 = (RuleCall)cIntAssignment.eContents().get(0);
		
		//WInt:
		//	int=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//int=INT
		public Assignment getIntAssignment() { return cIntAssignment; }
		
		//INT
		public RuleCall getIntINTTerminalRuleCall_0() { return cIntINTTerminalRuleCall_0; }
	}
	public class WFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.WFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cInt1Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cInt1INTTerminalRuleCall_0_0 = (RuleCall)cInt1Assignment_0.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInt2Assignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInt2INTTerminalRuleCall_2_0 = (RuleCall)cInt2Assignment_2.eContents().get(0);
		
		//WFloat:
		//	int1=INT '.' int2=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//int1=INT '.' int2=INT
		public Group getGroup() { return cGroup; }
		
		//int1=INT
		public Assignment getInt1Assignment_0() { return cInt1Assignment_0; }
		
		//INT
		public RuleCall getInt1INTTerminalRuleCall_0_0() { return cInt1INTTerminalRuleCall_0_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//int2=INT
		public Assignment getInt2Assignment_2() { return cInt2Assignment_2; }
		
		//INT
		public RuleCall getInt2INTTerminalRuleCall_2_0() { return cInt2INTTerminalRuleCall_2_0; }
	}
	public class TempFormulaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.TempFormula");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cApAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cApAPParserRuleCall_0_0 = (RuleCall)cApAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cAmpersandAmpersandKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cFaAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cFaTempFormulaParserRuleCall_1_2_0 = (RuleCall)cFaAssignment_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cVerticalLineVerticalLineKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cFoAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cFoTempFormulaParserRuleCall_2_2_0 = (RuleCall)cFoAssignment_2_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cExclamationMarkExclamationMarkKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cFnotAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cFnotTempFormulaParserRuleCall_3_2_0 = (RuleCall)cFnotAssignment_3_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOp2Assignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cOp2OP2TerminalRuleCall_4_1_0 = (RuleCall)cOp2Assignment_4_1.eContents().get(0);
		private final Assignment cF1Assignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cF1TempFormulaParserRuleCall_4_2_0 = (RuleCall)cF1Assignment_4_2.eContents().get(0);
		private final Assignment cF2Assignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cF2TempFormulaParserRuleCall_4_3_0 = (RuleCall)cF2Assignment_4_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOpfAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cOpfOPFTerminalRuleCall_5_1_0 = (RuleCall)cOpfAssignment_5_1.eContents().get(0);
		private final Assignment cFAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cFTempFormulaParserRuleCall_5_2_0 = (RuleCall)cFAssignment_5_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		
		//TempFormula:
		//	ap=AP
		//	| '(' '&&' fa+=TempFormula+ ')' | '(' '||' fo+=TempFormula+ ')' | '(' '!!' fnot=TempFormula ')' | '(' op2=OP2
		//	f1=TempFormula f2=TempFormula ')' | '(' opf=OPF f=TempFormula ')';
		@Override public ParserRule getRule() { return rule; }
		
		//ap=AP | '(' '&&' fa+=TempFormula+ ')' | '(' '||' fo+=TempFormula+ ')' | '(' '!!' fnot=TempFormula ')' | '(' op2=OP2
		//f1=TempFormula f2=TempFormula ')' | '(' opf=OPF f=TempFormula ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ap=AP
		public Assignment getApAssignment_0() { return cApAssignment_0; }
		
		//AP
		public RuleCall getApAPParserRuleCall_0_0() { return cApAPParserRuleCall_0_0; }
		
		//'(' '&&' fa+=TempFormula+ ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//'&&'
		public Keyword getAmpersandAmpersandKeyword_1_1() { return cAmpersandAmpersandKeyword_1_1; }
		
		//fa+=TempFormula+
		public Assignment getFaAssignment_1_2() { return cFaAssignment_1_2; }
		
		//TempFormula
		public RuleCall getFaTempFormulaParserRuleCall_1_2_0() { return cFaTempFormulaParserRuleCall_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }
		
		//'(' '||' fo+=TempFormula+ ')'
		public Group getGroup_2() { return cGroup_2; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_0() { return cLeftParenthesisKeyword_2_0; }
		
		//'||'
		public Keyword getVerticalLineVerticalLineKeyword_2_1() { return cVerticalLineVerticalLineKeyword_2_1; }
		
		//fo+=TempFormula+
		public Assignment getFoAssignment_2_2() { return cFoAssignment_2_2; }
		
		//TempFormula
		public RuleCall getFoTempFormulaParserRuleCall_2_2_0() { return cFoTempFormulaParserRuleCall_2_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_3() { return cRightParenthesisKeyword_2_3; }
		
		//'(' '!!' fnot=TempFormula ')'
		public Group getGroup_3() { return cGroup_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }
		
		//'!!'
		public Keyword getExclamationMarkExclamationMarkKeyword_3_1() { return cExclamationMarkExclamationMarkKeyword_3_1; }
		
		//fnot=TempFormula
		public Assignment getFnotAssignment_3_2() { return cFnotAssignment_3_2; }
		
		//TempFormula
		public RuleCall getFnotTempFormulaParserRuleCall_3_2_0() { return cFnotTempFormulaParserRuleCall_3_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_3() { return cRightParenthesisKeyword_3_3; }
		
		//'(' op2=OP2 f1=TempFormula f2=TempFormula ')'
		public Group getGroup_4() { return cGroup_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_0() { return cLeftParenthesisKeyword_4_0; }
		
		//op2=OP2
		public Assignment getOp2Assignment_4_1() { return cOp2Assignment_4_1; }
		
		//OP2
		public RuleCall getOp2OP2TerminalRuleCall_4_1_0() { return cOp2OP2TerminalRuleCall_4_1_0; }
		
		//f1=TempFormula
		public Assignment getF1Assignment_4_2() { return cF1Assignment_4_2; }
		
		//TempFormula
		public RuleCall getF1TempFormulaParserRuleCall_4_2_0() { return cF1TempFormulaParserRuleCall_4_2_0; }
		
		//f2=TempFormula
		public Assignment getF2Assignment_4_3() { return cF2Assignment_4_3; }
		
		//TempFormula
		public RuleCall getF2TempFormulaParserRuleCall_4_3_0() { return cF2TempFormulaParserRuleCall_4_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'(' opf=OPF f=TempFormula ')'
		public Group getGroup_5() { return cGroup_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_0() { return cLeftParenthesisKeyword_5_0; }
		
		//opf=OPF
		public Assignment getOpfAssignment_5_1() { return cOpfAssignment_5_1; }
		
		//OPF
		public RuleCall getOpfOPFTerminalRuleCall_5_1_0() { return cOpfOPFTerminalRuleCall_5_1_0; }
		
		//f=TempFormula
		public Assignment getFAssignment_5_2() { return cFAssignment_5_2; }
		
		//TempFormula
		public RuleCall getFTempFormulaParserRuleCall_5_2_0() { return cFTempFormulaParserRuleCall_5_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_3() { return cRightParenthesisKeyword_5_3; }
	}
	public class APElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.AP");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Keyword cPKeyword_2_0 = (Keyword)cAlternatives_2.eContents().get(0);
		private final Keyword cPKeyword_2_1 = (Keyword)cAlternatives_2.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		////terminal OPFN: //Temporal operators with 1 formula operand and a number
		////	'futr' | 'past' | 'withinf' | 'withinp' | 'lasts' | 'lasted'
		////;
		//AP:
		//	'(' '-' ('P' | 'p') '-' name=ID ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' '-' ('P' | 'p') '-' name=ID ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//('P' | 'p')
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//'P'
		public Keyword getPKeyword_2_0() { return cPKeyword_2_0; }
		
		//'p'
		public Keyword getPKeyword_2_1() { return cPKeyword_2_1; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_3() { return cHyphenMinusKeyword_3; }
		
		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	
	
	private final ModelElements pModel;
	private final SoftFormulaElements pSoftFormula;
	private final SoftAllTIElements pSoftAllTI;
	private final SoftTIElements pSoftTI;
	private final WeightElements pWeight;
	private final WIntElements pWInt;
	private final WFloatElements pWFloat;
	private final TempFormulaElements pTempFormula;
	private final TerminalRule tOP2;
	private final TerminalRule tOPF;
	private final APElements pAP;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public OltlGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pSoftFormula = new SoftFormulaElements();
		this.pSoftAllTI = new SoftAllTIElements();
		this.pSoftTI = new SoftTIElements();
		this.pWeight = new WeightElements();
		this.pWInt = new WIntElements();
		this.pWFloat = new WFloatElements();
		this.pTempFormula = new TempFormulaElements();
		this.tOP2 = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.OP2");
		this.tOPF = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "com.pourhashem.xtext.oltl.Oltl.OPF");
		this.pAP = new APElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.pourhashem.xtext.oltl.Oltl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	'Bound:' bound=INT ('SoftBound:' softBound=INT)?
	//	'Formula:' tempFormula=TempFormula ('SoftFormulae:' softFormulae+=SoftFormula*)?;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//SoftFormula:
	//	softAll=SoftAllTI | softAt=SoftTI;
	public SoftFormulaElements getSoftFormulaAccess() {
		return pSoftFormula;
	}
	
	public ParserRule getSoftFormulaRule() {
		return getSoftFormulaAccess().getRule();
	}
	
	//SoftAllTI:
	//	'(' 'soft' ap=AP id=ID? weight=Weight ')';
	public SoftAllTIElements getSoftAllTIAccess() {
		return pSoftAllTI;
	}
	
	public ParserRule getSoftAllTIRule() {
		return getSoftAllTIAccess().getRule();
	}
	
	//SoftTI:
	//	'(' 'soft' '(' '@' ap=AP ti=INT ')' id=ID? weight=Weight ')';
	public SoftTIElements getSoftTIAccess() {
		return pSoftTI;
	}
	
	public ParserRule getSoftTIRule() {
		return getSoftTIAccess().getRule();
	}
	
	//Weight:
	//	wInt=WInt | wFloat=WFloat;
	public WeightElements getWeightAccess() {
		return pWeight;
	}
	
	public ParserRule getWeightRule() {
		return getWeightAccess().getRule();
	}
	
	//WInt:
	//	int=INT;
	public WIntElements getWIntAccess() {
		return pWInt;
	}
	
	public ParserRule getWIntRule() {
		return getWIntAccess().getRule();
	}
	
	//WFloat:
	//	int1=INT '.' int2=INT;
	public WFloatElements getWFloatAccess() {
		return pWFloat;
	}
	
	public ParserRule getWFloatRule() {
		return getWFloatAccess().getRule();
	}
	
	//TempFormula:
	//	ap=AP
	//	| '(' '&&' fa+=TempFormula+ ')' | '(' '||' fo+=TempFormula+ ')' | '(' '!!' fnot=TempFormula ')' | '(' op2=OP2
	//	f1=TempFormula f2=TempFormula ')' | '(' opf=OPF f=TempFormula ')';
	public TempFormulaElements getTempFormulaAccess() {
		return pTempFormula;
	}
	
	public ParserRule getTempFormulaRule() {
		return getTempFormulaAccess().getRule();
	}
	
	//terminal OP2: //Propositional operators with 2 operands
	//	'->' | '<->' | 'until' | 'since' | 'release' | 'trigger';
	public TerminalRule getOP2Rule() {
		return tOP2;
	}
	
	//terminal OPF: //Temporal operators with 1 operands
	//	'next' | 'yesterday' | 'alw' | 'som' | 'alwf' | 'somf' | 'alwp' | 'somp';
	public TerminalRule getOPFRule() {
		return tOPF;
	}
	
	////terminal OPFN: //Temporal operators with 1 formula operand and a number
	////	'futr' | 'past' | 'withinf' | 'withinp' | 'lasts' | 'lasted'
	////;
	//AP:
	//	'(' '-' ('P' | 'p') '-' name=ID ')';
	public APElements getAPAccess() {
		return pAP;
	}
	
	public ParserRule getAPRule() {
		return getAPAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
